
name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*.x"
      - "master"
  push:
    branches:
      - "*.x"
      - "master"

env:
  fail-fast: true
  SYMFONY_DEPRECATIONS_HELPER: "max[self]=0&max[direct]=0"

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
        dependencies:
          - "highest"
        stability:
          - "stable"
        extra_constraint:
          - ""
        include:
          - dependencies: "lowest"
            php-version: "7.1"
          - dependencies: "highest"
            extra_constraint: "symfony/lts:v3"
            php-version: "7.3"
          - dependencies: "highest"
            stability: "dev"
            php-version: "7.3"
          - dependencies: "highest"
            stability: "dev"
            php-version: "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP with PCOV"
        uses: "shivammathur/setup-php@v2"
        if: "${{ matrix.php-version != '7.1' }}"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"

      - name: "Install PHP with XDebug"
        uses: "shivammathur/setup-php@v2"
        if: "${{ matrix.php-version == '7.1' }}"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "xdebug"
          ini-values: "zend.assertions=1"

      - name: "Use dev stability"
        run: "composer config minimum-stability dev"
        if: "${{ matrix.stability == 'dev' }}"

      - name: "Add extra constraint"
        run: "composer require --no-update ${{matrix.extra_constraint}}"
        if: "${{ contains(matrix.extra_constraint, '/') }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist"

      - name: "Configure deprecations helper"
        run: "echo SYMFONY_DEPRECATIONS_HELPER=weak >> $GITHUB_ENV"
        if: "${{ matrix.dependencies == 'lowest' }}"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"

      - name: "Upload coverage file"
        uses: "actions/upload-artifact@v2"
        if: "${{ ! contains(matrix.extra_constraint, '/') }}"
        with:
          name: "phpunit-${{ matrix.dependencies }}-${{ matrix.stability }}-${{ matrix.php-version }}.coverage"
          path: "coverage.xml"

      - name: "Upload coverage file, sanitize the name"
        uses: "actions/upload-artifact@v2"
        if: "${{ contains(matrix.extra_constraint, '/') }}"
        with:
          name: "phpunit-symfony-lts-${{ matrix.php-version }}.coverage"
          path: "coverage.xml"

  upload_coverage:
    name: "Upload coverage to Codecov"
    runs-on: "ubuntu-20.04"
    needs:
      - "phpunit"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Download coverage files"
        uses: "actions/download-artifact@v2"
        with:
          path: "reports"

      - name: "Upload to Codecov"
        uses: "codecov/codecov-action@v1"
        with:
          directory: reports
